---
- hosts: webservers
  name: Webserver assignment
  import_playbook: ../static-assignments/webservers.yml


- name: inport database
  host: webservers
  import_playbook: ../static-assignments/db.yml

- name: Loadbalancers assignment
  hosts: lb
  import_playbook: ../static-assignments/loadbalancers.yml
  when: load_balancer_is_required 








